-- Ejecutar en MySQL Workbench si ya tienes SanitApp instalado
USE sanitapp;

CREATE TABLE IF NOT EXISTS responsables (
  id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre_completo VARCHAR(150) NOT NULL,
  activo          TINYINT(1) NOT NULL DEFAULT 1,
  creado_en       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_responsables_nombre (nombre_completo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO responsables (nombre_completo) VALUES
('PEDRO ARMANDO PEÑA ARENAS'),
('JHON FREDY MORALES ARIAS'),
('LEONARDO CORREA MANRIQUE'),
('ALEXIS DARIO BARRAZA GARCIA'),
('ALEXANDER JIMENEZ RODRIGUEZ'),
('HELVER JOSE FLOREZ PEDROZO'),
('HENRY ARMANDO LOPEZ PINTO'),
('EDWARD ALEXANDER ARDILA SALAS'),
('LUIS HERNANDO LOBO VELASQUEZ'),
('CARLOS ALFREDO GONZALEZ DIAZ'),
('ANDREY ALIRIO PARADA SILVA'),
('JORGE ELIECER TORRES'),
('MANZUR NAIN MANZANO LIZARAZO'),
('LUDDALLAMON PINTO RANGEL'),
('JOSE MIGUEL MARMOL CAPATAZ'),
('JOSE DANIEL BAUTISTA CRUZ'),
('DUBIAN ERNEY RINCON MENDOZA'),
('JOHN EDWIN BLANCO CAVIEDES'),
('CRISTHIAN OMAR QUINTERO REYES'),
('ANDRES FELIPE BOHORQUEZ ANGARITA'),
('MATHA JANETH JAIMES VARGAS'),
('PEDRO JOSE HERNANDEZ DURAN');
